//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapelesApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPP_MAESTRO_COSTO_PAPEL
    {
        public decimal ID_EMPRESA { get; set; }
        public decimal ID_MAESTRO_PAPELES { get; set; }
        public Nullable<decimal> MCP_COSTO_PROMEDIO_Q { get; set; }
        public Nullable<decimal> MCP_ULTIMO_COSTO_Q { get; set; }
        public Nullable<decimal> MCP_COSTO_PROMEDIO_USD { get; set; }
        public Nullable<decimal> MCP_ULTIMO_COSTO_USD { get; set; }
    
        public virtual IPP_MAESTRO_PAPELES IPP_MAESTRO_PAPELES { get; set; }
    }
}
