//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapelesApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPP_MAESTRO_PAPELES_BK
    {
        public IPP_MAESTRO_PAPELES_BK()
        {
            this.IPP_MAESTRO_COSTO_PAPEL_BK = new HashSet<IPP_MAESTRO_COSTO_PAPEL_BK>();
        }
    
        public decimal MP_ID_PAPEL { get; set; }
        public Nullable<decimal> MP_ID_TIPO_PAPEL { get; set; }
        public Nullable<decimal> MP_CALIBRE { get; set; }
        public Nullable<decimal> MP_ANCHO { get; set; }
        public string MP_CODIGO_ALTERNO { get; set; }
    
        public virtual ICollection<IPP_MAESTRO_COSTO_PAPEL_BK> IPP_MAESTRO_COSTO_PAPEL_BK { get; set; }
        public virtual IPP_TIPOS_DE_PAPEL_BK IPP_TIPOS_DE_PAPEL_BK { get; set; }
    }
}
