//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapelesApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class IPP_MAESTRO_PAPELES
    {
        public IPP_MAESTRO_PAPELES()
        {
            this.IPP_MAESTRO_COSTO_PAPEL = new HashSet<IPP_MAESTRO_COSTO_PAPEL>();
        }
    
        public decimal MP_ID_PAPEL { get; set; }

        [DisplayName("Tipo de Papel")]
        public Nullable<decimal> MP_ID_TIPO_PAPEL { get; set; }
        [DisplayName("Calibre")]
        public Nullable<decimal> MP_CALIBRE { get; set; }
        [DisplayName("Ancho")]
        public Nullable<decimal> MP_ANCHO { get; set; }
        [DisplayName("Codigo")]
        public string MP_CODIGO_ALTERNO { get; set; }
    
        public virtual ICollection<IPP_MAESTRO_COSTO_PAPEL> IPP_MAESTRO_COSTO_PAPEL { get; set; }
        public virtual IPP_TIPOS_DE_PAPEL IPP_TIPOS_DE_PAPEL { get; set; }
    }
}
