//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapelesApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class IPP_TIPOS_DE_PAPEL
    {
        public IPP_TIPOS_DE_PAPEL()
        {
            this.IPP_MAESTRO_PAPELES = new HashSet<IPP_MAESTRO_PAPELES>();
        }
        
        public decimal TDP_CODIGO { get; set; }
        [DisplayName("Clave")]
        public string TDP_CLAVE { get; set; }
        public string TDP_DESCRIPCION { get; set; }
        public string TDP_COLOR { get; set; }
        public string TDP_CALIDAD_DE_PAPEL { get; set; }
        public string TDP_CUENTA_CONTABLE { get; set; }
        public Nullable<decimal> TDP_FACTOR_CONTABLE { get; set; }
    
        public virtual ICollection<IPP_MAESTRO_PAPELES> IPP_MAESTRO_PAPELES { get; set; }
    }
}
