//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapelesApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<IPP_MAESTRO_COSTO_PAPEL> IPP_MAESTRO_COSTO_PAPEL { get; set; }
        public DbSet<IPP_MAESTRO_COSTO_PAPEL_BK> IPP_MAESTRO_COSTO_PAPEL_BK { get; set; }
        public DbSet<IPP_MAESTRO_PAPELES> IPP_MAESTRO_PAPELES { get; set; }
        public DbSet<IPP_MAESTRO_PAPELES_BK> IPP_MAESTRO_PAPELES_BK { get; set; }
        public DbSet<IPP_TIPOS_DE_PAPEL> IPP_TIPOS_DE_PAPEL { get; set; }
        public DbSet<IPP_TIPOS_DE_PAPEL_BK> IPP_TIPOS_DE_PAPEL_BK { get; set; }
    }
}
